version: 2.1

commands:
  test:
    steps:
      - run:
          name: "test"
          command: |
            scripts/migrate.sh
            make test

executors:
  golang-spanner:
    docker:
      - image: sodefrin/spanner-emulator-ci:287.0.0
        environment:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_PROJECT_ID: spanner-test-project
          SPANNER_INSTANCE_ID: spanner-test-instance
          SPANNER_DATABASE_ID: spanner-test-database
          DDL: db/schema.sql

jobs:
  test:
    executor: golang-spanner
    working_directory: /go/src/github.com/sodefrin/spanner-emulator-ci
    steps:
      - checkout
      - test

workflows:
  version: 2
  test:
    jobs:
      - test
