version: 2.1

commands:
  go:
    steps:
      - run:
          name: "install go"
          command: |
             scripts/go.sh
             
  migrate:
    steps:
      - run:
          name: "migrate db"
          command: |
             scripts/migrate.sh
             
  test:
    steps:
      - run:
          name: "make test"
          command: |
              make test

executors:
  golang-spanner:
    docker:
      - image: google/cloud-sdk:287.0.0-debian_component_based
        environment:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_PROJECT_ID: spanner-test-project
          SPANNER_INSTANCE_ID: spanner-test-instance
          SPANNER_DATABASE_ID: spanner-test-database
          DDL: db/schema.sql

jobs:
  test:
    executor: golang-spanner
    working_directory: /go/src/github.com/sodefrin/spanner-emulator-ci
    steps:
      - checkout
      - go
      - migrate

workflows:
  version: 2
  test:
    jobs:
      - test
